### ISSUE TITLE
Samples?

### ISSUE THREAD

**Issue by VictorBebnev** [HaiFengZeng/clari_wavenet_vocoder#3]
Hi! 
You project looks pretty good. Do you have any audio results of this project?
Thanks!

**Comment by HaiFengZeng** [comment]
not good yet, hope we can make it better.
[ljspeech.zip](https://github.com/HaiFengZeng/clari_wavenet_vocoder/files/2387274/ljspeech.zip)

**Comment by VictorBebnev** [comment]
Thank you.
